export const SIDEBAR_DISPLAY_OPTIONS = {
  groupChat: 'groupChatUsers',
  personalChat: 'personalChatUsers',
  conversations: 'conversations',
};

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const GET_CONVERSATIONS_FAIL = 'GET_CONVERSATIONS_FAIL';
export const GET_CHAT_MESSAGES = 'GET_CHAT_MESSAGES';
export const GET_CHAT_MESSAGES_FAIL = 'GET_CHAT_MESSAGES_FAIL';
export const SET_DISPLAY_CONVERVATION_ID = 'SET_DISPLAY_CONVERVATION_ID';
export const SET_DISPLAY_SIDEBAR_COMPONENT = 'SET_DISPLAY_SIDEBAR_COMPONENT';
export const SELECT_GROUP_CHAT_USERS = 'SELECT_GROUP_CHAT_USERS';
export const UNSELECT_GROUP_CHAT_USER = 'UNSELECT_GROUP_CHAT_USER';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';
export const CREATE_CONVERSATION_SUCCESS = 'CREATE_CONVERSATION_SUCCESS';
export const CREATE_GROUP_CONVERSATION_FAIL = 'CREATE_GROUP_CONVERSATION_FAIL';
export const CREATE_PERSONAL_CONVERSATION_FAIL = 'CREATE_PERSONAL_CONVERSATION_FAIL';
export const CLEAR_SELECT_USER = 'CLEAR_SELECT_USER';
export const SET_CHECK_FOR_MESSAGE = 'SET_CHECK_FOR_MESSAGE';
export const GET_NEW_CHAT_SUCCESS = 'GET_NEW_CHAT_SUCCESS';
export const SEND_CHAT_FAIL = 'SEND_CHAT_FAIL';
